### PR TITLE
Changed unix socket connection to secure, mutual TLS port connection

### PR DESCRIPTION
**Pull request by michelvocks**

### CODE REVIEW

**Comment by michelvocks** [comment]
@Skarlso this change will also already introduce job parameters. Every job must then accept `map[string]string` as parameter. What do you think? 🤗

**Comment by Skarlso** [comment]
@michelvocks Love it!

**Comment by michelvocks** [comment]
Great. Let's hold this PR until next release.

**Review by Skarlso — APPROVED** [review]

**Comment by michelvocks** [comment]
I will close this PR because it's included in #2

**Pull request closed without merging**
